version: '3'

services:
  postgres:
    image: postgres:14.8
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deezer
    ports:
      - 5435:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - 6382:6379
