version: '3'

services:
  postgres:
    image: postgres:14.8
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deezer
    ports:
      - 5435:5432